### ISSUE TITLE
Efficient way to produce table from vector of structs?

### ISSUE THREAD

**Issue by aharpervc** [Nukesor/comfy-table#68] opened 2022-03-03 22:23 UTC
Hi, I'm experimenting with this library and I have a question. I have a vector containing custom structs, where each struct field should be a table column. I'm trying to figure out how to produce this table efficiently. Right now I'm basically doing this:

```rust
    let mut table = Table::new();
    table.load_preset(UTF8_FULL)
        .set_content_arrangement(ContentArrangement::Dynamic)
        .set_header(vec![
            Cell::new("a"),
            Cell::new("b"),
            Cell::new("c"),
            Cell::new("d"),
            Cell::new("e"),
            Cell::new("f"),
            Cell::new("g"),
        ]);

    // let things: Vec<Thing> = get_things(...);
    for d in things.iter() {
        table.add_row(vec![
            Cell::new(&d.a),
            Cell::new(&d.b),
            Cell::new(&d.c),
            Cell::new(&d.d),
            Cell::new(&d.e),
            Cell::new(&d.f),
            Cell::new(&d.g),
        ]);
    }
```
This works, and produces the correct output, but it seems a little slow with ~670 structs in the vector. It gets a bit faster if I turn off dynamic layout, but without that feature the table is sized incorrectly so I think I need it to be enabled.

1. Is there a more efficient way to load a vector of structs instead of iter + add_row? For example, I think the `tabled` crate can accept that data structure directly (maybe it's doing iter + add_row internally though I don't know)
2. Is there a way to size the table to the terminal width without dynamic content arrangement (if that's actually the right choice regardless?)
3. Do you have any other recommendations for this situation?

**Comment by Nukesor** [comment] 2022-03-04 15:20
`tabled` accepts data structures via the `Tabled` trait, which simply implements the exact same thing you're doing over here as well, that is returning a vector with all fields of the struct.

As you've noticed, enabling dynamic content arrangement takes a bit of time. Though I'm confused that this takes so long that you're experiencing lags.

Do you run this in release or debug mode?

**Comment by aharpervc** [comment] 2022-03-04 18:51
> Do you run this in release or debug mode? In case you're running it in debug mode, please try again with the `--release` flag and check if this is still the case.

Yes, it was debug mode. It isn't critical that all columns be sized dynamically to their content. Is it possible to set a fixed width for some columns, and let only one or two columns size dynamically to scale up to the max width? Or if not that, then I could probably compute each column's fixed width myself if there's an API for that.

**Comment by Nukesor** [comment] 2022-03-05 18:54
Check the [constriant](https://docs.rs/comfy-table/latest/comfy_table/struct.Column.html#method.set_constraint) api on columns

**Comment by Nukesor** [comment] 2022-03-06 11:01
If you have no additional questions, feel free to close this issue :)

**Comment by aharpervc** [comment] 2022-03-07 22:25
It's still all somewhat un-ergonomic to do this. I don't think it's even that wild of an idea, is it? I basically never want the table _rows_ to wrap. Some cell contents can wrap if necessary, but if not necessary then I'd prefer them to not wrap. There doesn't seem to be a way to tell comfy-table "the sum of the cell widths should never exceed x". 

However, I think I have something that's sort of working. Are there any improvements here you can recommend?

```rust
// above example, with dynamic sizing turned off, and this is added before appending rows
// added the terminal_size crate 
let dimensions = terminal_size();
let (terminal_size::Width(w), terminal_size::Height(_)) = dimensions.unwrap_or_else(|| (terminal_size::Width(80 * 2), terminal_size::Height(0)));

let variable_size_column_count = 4;
let available_width_for_variable_sizing = w - (6 + 24 + 3);
let variable_size_column_max_width = (available_width_for_variable_sizing / variable_size_column_count) - 2;

// note: widths need to include padding
table.get_column_mut(0).unwrap().set_constraint(ColumnConstraint::Absolute(Width::Fixed(6)));
table.get_column_mut(1).unwrap().set_constraint(ColumnConstraint::UpperBoundary(Width::Fixed(variable_size_column_max_width)));
table.get_column_mut(2).unwrap().set_constraint(ColumnConstraint::Absolute(Width::Fixed(24)));
table.get_column_mut(3).unwrap().set_constraint(ColumnConstraint::UpperBoundary(Width::Fixed(variable_size_column_max_width)));
table.get_column_mut(4).unwrap().set_constraint(ColumnConstraint::UpperBoundary(Width::Fixed(variable_size_column_max_width)));
table.get_column_mut(5).unwrap().set_constraint(ColumnConstraint::UpperBoundary(Width::Fixed(variable_size_column_max_width)));
table.get_column_mut(6).unwrap().set_constraint(ColumnConstraint::Absolute(Width::Fixed(3)));


```

**Comment by aharpervc** [comment] 2022-03-07 22:52
> Do you really still have performance issues with absolute widths on a few columns and release mode?

I haven't noticed a performance issue when not using dynamic arrangement mode, even in debug mode. Mixing the fixed widths and the manually calculated upper boundaries _does_ seem to work, which is why I shared that snippet.

It just seems like quite a bit of code, which is why I was more asking about proper patterns & ergonomics more than anything.

> A few stats and your PC's specs would be awesome. We could do some profiling and speed up the program.

Right, I get it.

- Windows 10 x64 21H1
- Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
- 16GB ram

```
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\aharper\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.58.1 (db9d1b20b 2022-01-20)
```

**Comment by Nukesor** [comment] 2022-03-08 00:38
Sorry if my question was not clear.
I meant whether you still have performance issues when using dynamic content arrangement and `release` builds.
I'm just confused, as I tried benchmarks with a few pretty large tables that contained huge texts and it still finished in less than `1 ms`.

**Comment by Nukesor** [comment] 2022-03-08 13:43
One more thing.
The whole constraint code could be reduced to this:

```
use comfy_table::ColumnConstraint::*;

table.set_constraints(vec![
    Absolute(Width::Fixed(6)),
    UpperBoundary(Width::Fixed(variable_size_column_max_width)),
    Absolute(Width::Fixed(24)),
    UpperBoundary(Width::Fixed(variable_size_column_max_width)),
    UpperBoundary(Width::Fixed(variable_size_column_max_width)),
    UpperBoundary(Width::Fixed(variable_size_column_max_width)),
    Absolute(Width::Fixed(3)),
]);
```

**Comment by Nukesor** [comment] 2022-03-08 14:04
One more thing. I did some benchmarks, and there seems to be a massive performance regression somewhere over the last few months.

I'll try to pinpoint this, so we can speed things up again.

**Closed** 2022-03-08 15:29 UTC

**Comment by Nukesor** [comment] 2022-03-08 16:20
> Yes, the behavior is similar with both debug & release with dynamic content arrangement enabled. The output "hitches" or pauses as the table is being printed. I can't easily show a screenshot since I can't show the actual data in this table, but the code I'm using is basically what I've shared here.

I'm still super curious. I just wrote a new benchmark with a 10 column, 500 row table, where each cell had text between 2 and 100 characters and it finished in ~20ms in dynamic mode without any constraints.
Maybe you run into some weird edge-case?

Is this example similar to your use-case? Are you handling long texts?
